using UnityEngine;
using UnityEngine.UI;
/// <summary>
/// ƒŠƒ\[ƒX‚ğŠÇ—
/// ‘”‚â‰ÁZAŒ¸Z‚·‚éƒƒ\ƒbƒh‚ğ‚Â
/// ‰ÁZ‚ÉŠÖ‚·‚é•Ï”i2‚ÂjF–ˆ•b‰ÁZ‚·‚é•Ï”EƒNƒŠƒbƒN‚Ì‚½‚Ñ‚É‰ÁZ‚·‚é•Ï”
/// </summary>
public class ResourceManager : MonoBehaviour
{
<<<<<<< HEAD
    [Tooltip("ƒŠƒ\[ƒXŠÇ—‚ğ‚·‚éƒNƒ‰ƒX‚ÌƒCƒ“ƒXƒ^ƒ“ƒX")] ResourceManager Instance = default;
=======
    [SerializeField, Tooltip("ƒŠƒ\[ƒX‚Ì‘—Ê")] public static ResourceManager Instance = default;
>>>>>>> 6d490c4 ([update] ã€ŒResourceManager.Instance.é–¢æ•°ã€ã§å‘¼ã¹ã‚‹ã‚ˆã†ã«ã—ãŸã€‚)
    [Header("ƒŠƒ\[ƒX‚Ì‘—Ê")]
    [SerializeField, Tooltip("ƒŠƒ\[ƒX‚Ì‘—Ê")] double _resourceTotalAmount = default;
    [Header("ƒeƒLƒXƒgiƒŠƒ\[ƒX‚Ì‘—Êj")]
    [SerializeField, Tooltip("ƒeƒLƒXƒgiƒŠƒ\[ƒX‚Ì‘—Êj")] Text _textRTA = default;
    [Header("–ˆ•b‰ÁZ‚·‚é‘—Ê")]
    [SerializeField, Tooltip("–ˆ•b‰ÁZ‚·‚é‘—Ê")] float _addAmountEverySecond = default;

    #region ƒvƒƒpƒeƒB
    public double ResourceTotalAmount { get => _resourceTotalAmount; /*set => _resourceTotalAmount = value;*/ }
    #endregion

    void Awake()
    {
        if (!Instance)
        {
            Instance = this;
        }
    }

    void Start()
    {
        _resourceTotalAmount = 0;
        _addAmountEverySecond = 0;
    }

    void Update()
    {
        // ŠÔŒo‰ß‚Æ‚Æ‚à‚É‰ÁZ
        _resourceTotalAmount += _addAmountEverySecond * Time.deltaTime;
        _textRTA.text = _resourceTotalAmount.ToString("000,000.0");
    }

    /// <summary>
    /// –ˆ•b‰ÁZ‚·‚é‚Æ‚«‚ÌA‰ÁZ—Ê‚ğ‘‚â‚·ŠÖ”
    /// </summary>
    /// <param name="value"></param>
    public void AddEverySecond(float value)
    {
        _addAmountEverySecond += value;
    }

    /// <summary>
    /// ƒNƒŠƒbƒN‘ÎÛ‚ğƒNƒŠƒbƒN‚·‚é‚Æ‚«‚ÉŒÄ‚Ô
    /// ƒNƒŠƒbƒN‚Ì‚½‚Ñ‚É‰ÁZ
    /// </summary>
    /// <param name="value"></param>
    public void AddResource(int value)
    {
        _resourceTotalAmount += value;
    }

    /// <summary>
    /// iƒVƒ‡ƒbƒv‚ÅjƒŠƒ\[ƒX‚ğÁ”ï‚·‚éˆ—
    /// Š‚µ‚Ä‚¢‚éƒŠƒ\[ƒX‚Ì‘—Ê‚ğ’´‚¦‚Ä‚¢‚½‚çA‰½‚à‚µ‚È‚¢
    /// </summary>
    /// <param name="value">Á”ï—Ê</param>
    public void UseResource(float value)
    {
        if (value <= ResourceTotalAmount)
            _resourceTotalAmount -= value;
        else
            Debug.LogWarning("ƒRƒXƒg‚ªŠ‚µ‚Ä‚¢‚éƒŠƒ\[ƒX—Ê‚ğ’´‚¦‚Ä‚¢‚Ü‚·B");
    }
}